"""Render a run-history detail into a shareable report (HTML or Markdown).

Pure functions over the dict returned by ``HistoryService.get_run`` — no I/O,
no DB access — so they are trivially testable and safe to call from the router.
The HTML is fully self-contained (inline CSS, no external assets) so a saved
file opens correctly offline and can be handed to a client as engagement
evidence.
"""
from __future__ import annotations

import html
from datetime import datetime
from typing import Any, Optional

BEACON_URL = "https://beacon-tester.vercel.app"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _fmt_ms(value: Optional[float]) -> str:
    if value is None:
        return "—"
    try:
        return f"{round(float(value))} ms"
    except (TypeError, ValueError):
        return "—"


def _fmt_rps(value: Optional[float]) -> str:
    try:
        return f"{float(value):.1f}" if value is not None else "—"
    except (TypeError, ValueError):
        return "—"


def _fmt_duration(ms: Optional[float]) -> str:
    if not ms:
        return "—"
    seconds = float(ms) / 1000.0
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes, secs = divmod(int(seconds), 60)
    return f"{minutes}m {secs}s"


def _fmt_dt(value: Optional[str]) -> str:
    if not value:
        return "—"
    try:
        return datetime.fromisoformat(value).strftime("%Y-%m-%d %H:%M:%S UTC")
    except (TypeError, ValueError):
        return str(value)


def _success_rate(m: dict) -> str:
    attempts = m.get("attempts") or 0
    if not attempts:
        return "—"
    return f"{(m.get('success', 0) / attempts) * 100:.1f}%"


def _summary_rows(detail: dict) -> list[tuple[str, str]]:
    m = detail.get("metrics") or {}
    return [
        ("Attempts", str(m.get("attempts", 0))),
        ("Success", f"{m.get('success', 0)} ({_success_rate(m)})"),
        ("Rate-limited", str(m.get("rate_limited", 0))),
        ("Errors", str(m.get("errors", 0))),
        ("Avg RPS", _fmt_rps(m.get("average_rps"))),
        ("Peak RPS", _fmt_rps(m.get("peak_rps"))),
        ("Latency p50", _fmt_ms(m.get("p50_ms"))),
        ("Latency p95", _fmt_ms(m.get("p95_ms"))),
        ("Latency p99", _fmt_ms(m.get("p99_ms"))),
        ("Latency max", _fmt_ms(m.get("max_latency_ms"))),
    ]


def _meta_rows(detail: dict) -> list[tuple[str, str]]:
    return [
        ("Project", str(detail.get("project_name") or "—")),
        ("Target", str(detail.get("target_name") or "—")),
        ("Mode", str(detail.get("mode") or "—")),
        ("Status", str(detail.get("status") or "—")),
        ("Started", _fmt_dt(detail.get("started_at"))),
        ("Completed", _fmt_dt(detail.get("completed_at"))),
        ("Duration", _fmt_duration(detail.get("duration_ms"))),
    ]


# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #
def render_markdown(detail: dict) -> str:
    lines: list[str] = []
    title = detail.get("target_name") or "Run"
    lines.append(f"# Beacon Run Report — {title}")
    lines.append("")
    for k, v in _meta_rows(detail):
        lines.append(f"- **{k}:** {v}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    for k, v in _summary_rows(detail):
        lines.append(f"| {k} | {v} |")
    lines.append("")

    steps = detail.get("steps") or []
    if len(steps) > 1:
        lines.append("## Steps")
        lines.append("")
        lines.append("| # | Endpoint | Method | Status |")
        lines.append("| --- | --- | --- | --- |")
        for s in steps:
            lines.append(
                f"| {s.get('sequence', '')} | {s.get('endpoint_name') or '—'} "
                f"| {s.get('method') or '—'} | {s.get('status') or '—'} |"
            )
        lines.append("")

    lines.append("---")
    lines.append(f"Generated by [Beacon]({BEACON_URL}) · {_fmt_dt(detail.get('completed_at') or detail.get('started_at'))}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# HTML
# --------------------------------------------------------------------------- #
def _rows_html(rows: list[tuple[str, str]]) -> str:
    return "".join(
        f"<tr><th>{html.escape(k)}</th><td>{html.escape(v)}</td></tr>" for k, v in rows
    )


def _stat_cards(detail: dict) -> str:
    m = detail.get("metrics") or {}
    cards = [
        ("Attempts", str(m.get("attempts", 0)), "#0ea5e9"),
        ("Success", _success_rate(m), "#10b981"),
        ("Rate-limited", str(m.get("rate_limited", 0)), "#f59e0b"),
        ("Errors", str(m.get("errors", 0)), "#ef4444"),
        ("p95", _fmt_ms(m.get("p95_ms")), "#8b5cf6"),
        ("Peak RPS", _fmt_rps(m.get("peak_rps")), "#0ea5e9"),
    ]
    return "".join(
        f'<div class="card"><div class="v" style="color:{c}">{html.escape(v)}</div>'
        f'<div class="l">{html.escape(l)}</div></div>'
        for l, v, c in cards
    )


def _steps_html(detail: dict) -> str:
    steps = detail.get("steps") or []
    if len(steps) <= 1:
        return ""
    rows = "".join(
        f"<tr><td>{html.escape(str(s.get('sequence', '')))}</td>"
        f"<td>{html.escape(str(s.get('endpoint_name') or '—'))}</td>"
        f"<td>{html.escape(str(s.get('method') or '—'))}</td>"
        f"<td>{html.escape(str(s.get('status') or '—'))}</td></tr>"
        for s in steps
    )
    return (
        '<h2>Steps</h2><table class="grid">'
        "<thead><tr><th>#</th><th>Endpoint</th><th>Method</th><th>Status</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def render_html(detail: dict) -> str:
    title = html.escape(str(detail.get("target_name") or "Run"))
    generated = _fmt_dt(detail.get("completed_at") or detail.get("started_at"))
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Beacon Report — {title}</title>
<style>
  :root {{ color-scheme: light; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; background: #f4f5f7; color: #111827; }}
  .wrap {{ max-width: 820px; margin: 0 auto; padding: 32px 20px 64px; }}
  header {{ display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }}
  header .dot {{ width: 12px; height: 12px; border-radius: 50%; background: #0ea5e9;
                box-shadow: 0 0 0 4px rgba(14,165,233,.2); }}
  header h1 {{ font-size: 20px; margin: 0; }}
  .sub {{ color: #6b7280; font-size: 13px; margin: 0 0 24px 24px; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
           gap: 12px; margin: 20px 0 28px; }}
  .card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px;
          text-align: center; }}
  .card .v {{ font-size: 24px; font-weight: 700; }}
  .card .l {{ font-size: 12px; color: #6b7280; margin-top: 4px; }}
  h2 {{ font-size: 15px; margin: 28px 0 10px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
          border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 10px 14px; font-size: 13px;
           border-bottom: 1px solid #f0f1f3; }}
  table.meta th {{ width: 160px; color: #6b7280; font-weight: 600; }}
  table.grid thead th {{ background: #f9fafb; color: #6b7280; font-size: 12px; }}
  tr:last-child td, tr:last-child th {{ border-bottom: none; }}
  footer {{ margin-top: 32px; font-size: 12px; color: #9ca3af; text-align: center; }}
  footer a {{ color: #0ea5e9; text-decoration: none; }}
</style></head>
<body><div class="wrap">
  <header><span class="dot"></span><h1>Beacon Run Report</h1></header>
  <p class="sub">{title}</p>

  <div class="cards">{_stat_cards(detail)}</div>

  <h2>Overview</h2>
  <table class="meta"><tbody>{_rows_html(_meta_rows(detail))}</tbody></table>

  <h2>Metrics</h2>
  <table class="meta"><tbody>{_rows_html(_summary_rows(detail))}</tbody></table>

  {_steps_html(detail)}

  <footer>Generated by <a href="{BEACON_URL}">Beacon</a> · {html.escape(generated)}</footer>
</div></body></html>
"""
